version: '3'
services:
  mongo:
    image: 'mongo:4.4'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MM_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MM_MONGO_PWD}
      - MONGO_DEVS=${MONGO_DEVS}
      - MONGO_DEV_PWD=${MONGO_DEV_PWD}
      - MONGO_PORT=${MONGO_PORT}
      - MM_DB=${MM_DB}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - ${SERVER_DIRECTORY_MONGO}:/data/db
      - ${SERVER_DIRECTORY}/restore:/restore
      - ${SERVER_DIRECTORY}/log:/var/log/mongodb
      - ${SERVER_DIRECTORY}/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
  es:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.1'
    container_name: es
    restart: always
    environment:
      - node.name=es
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '${ES_PORT}:9200'
    volumes:
      - ${SERVER_DIRECTORY}/es:/usr/share/elasticsearch/data
  minio:
    image: quay.io/minio/minio:RELEASE.2022-03-17T06-34-49Z
    command: server /data
    hostname: minio
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
    volumes:
      - ${SERVER_DIRECTORY}/minio:/data
  proxy:
    depends_on:
      - minio1
      - api
      - client
      - kg
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '${PROXY_PORT}:80'
  api:
    image: dukematsci/dev-restful
    depends_on:
      - es
      - mongo
    restart: always
    environment:
      - DB_USERNAME=${MONGO_DEVS}
      - DB_PASSWORD=${MONGO_DEV_PWD}
      - MM_DB=${MM_DB}
      - MONGO_ADDRESS=${MONGO_ADDRESS}
      - MONGO_PORT=${MONGO_PORT}
      - TKNS=${TKNS}
      - ESADDRESS=${ESADDRESS}
      - PORT=${PORT}
      - MINIO_PORT=${MINIO_PORT}
    ports:
      - '${PORT}:${PORT}'
  client:
    image: dukematsci/dev-app
    environment:
      - API_PORT=${PORT}
      - MINIO_PORT=${MINIO_PORT}
    ports:
      - '${CLIENT_PORT}:4000'
  # kg:
  #   image: 'stain/jena-fuseki:4.0.0'
  #   restart: always
  #   environment:
  #     - ADMIN_PASSWORD=${ADMIN_PASSWORD}
  #     - JVM_ARGS=-Xmx3g
  #   ports:
  #     - '${KG_PORT}:3030'
  #   volumes:
  #     - ${SERVER_DIRECTORY}/fuseki:/fuseki
volumes:
  ${SERVER_DIRECTORY}:
  ${SERVER_DIRECTORY_MONGO}: